# Generated by Django 3.1.3 on 2021-03-04 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ph', models.IntegerField()),
                ('message', models.TextField()),
                ('agree', models.BooleanField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consult', models.NullBooleanField()),
                ('memo', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.info')),
            ],
        ),
    ]
