# Generated by Django 3.1.3 on 2021-03-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='consult',
            field=models.BooleanField(null=True),
        ),
    ]
