# Generated by Django 3.1.3 on 2021-03-04 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_answer_consult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='agree',
        ),
    ]
