# Generated by Django 3.1.3 on 2021-03-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_answer_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='agree',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
