# Generated by Django 3.1.3 on 2021-03-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_info_agree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='agree',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='info',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='ph',
            field=models.CharField(max_length=30),
        ),
    ]
